### Fresh test register
POST http://127.0.0.1:5000/register
Content-Type: application/json

{
  "username": "debuguser",
  "password": "debugpass123"
}

### Fresh test login
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
  "username": "debuguser",
  "password": "debugpass123"
}
